import numpy as np
import pandas as pd


"""
Candidate Flight Connection Generator Module.

DISTINCTION NOTICE:
-------------------
The connections generated by this module are schedule-feasible CANDIDATE flight connections
constructed strictly from published flight schedules and operational timestamps (UTC).
They DO NOT represent observed passenger bookings, passenger flow, ticketed itineraries,
or PNR / ticket data. They indicate pure operational network connectivity options between
inbound and outbound flight legs.
"""


REQUIRED_COLUMNS = [
    "flight_id",
    "carrier",
    "origin",
    "destination",
    "scheduled_departure_utc",
    "scheduled_arrival_utc",
]


def validate_flight_fact_schema(df: pd.DataFrame) -> None:
    """
    Validate that the input dataframe contains all required columns for connection generation.
    """
    missing = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError(
            f"Input dataframe is missing required columns for connection generation: {missing}. "
            f"Expected Fact_Flight_Operation schema columns."
        )


def generate_candidate_connections(
    df: pd.DataFrame,
    min_connection_min: int = 45,
    max_connection_min: int = 240,
    same_carrier_only: bool = False,
    filter_cancelled: bool = True,
    allow_circular: bool = False,
) -> pd.DataFrame:
    """
    Generate schedule-feasible candidate flight connections from Fact_Flight_Operation data.

    A candidate connection is defined as a two-leg flight sequence:
        Flight A (Inbound):  origin -> connection_airport
        Flight B (Outbound): connection_airport -> destination

    Feasibility condition:
        min_connection_min <= (outbound.scheduled_departure_utc - inbound.scheduled_arrival_utc) <= max_connection_min

    Parameters:
        df (pd.DataFrame): Fact_Flight_Operation table containing flight segments.
        min_connection_min (int): Minimum connection window in minutes (default 45 min).
        max_connection_min (int): Maximum connection window in minutes (default 240 min).
        same_carrier_only (bool): If True, restrict to online connections (same carrier). Default False.
        filter_cancelled (bool): If True, exclude cancelled or diverted flights. Default True.
        allow_circular (bool): If True, allow connections where origin == destination (round-trip). Default False.

    Returns:
        pd.DataFrame: Candidate connection pairs with preserved inbound/outbound timestamps,
                      connection metrics, and flight metadata.
    """
    validate_flight_fact_schema(df)

    if df.empty:
        return pd.DataFrame()

    # Filter invalid or missing UTC timestamps
    valid_df = df[
        df["scheduled_arrival_utc"].notna() & df["scheduled_departure_utc"].notna()
    ].copy()

    # Filter cancelled / diverted flights if requested
    if filter_cancelled:
        if "is_cancelled" in valid_df.columns:
            valid_df = valid_df[valid_df["is_cancelled"] == False]
        if "is_diverted" in valid_df.columns:
            valid_df = valid_df[valid_df["is_diverted"] == False]

    if valid_df.empty:
        return pd.DataFrame()

    min_delta = pd.Timedelta(minutes=min_connection_min)
    max_delta = pd.Timedelta(minutes=max_connection_min)

    # Group flights by connection airport to avoid N x N global join
    # Inbound flights arrive at 'destination' (which is the connection airport)
    # Outbound flights depart from 'origin' (which is the connection airport)
    inbound_by_airport = dict(list(valid_df.groupby("destination")))
    outbound_by_airport = dict(list(valid_df.groupby("origin")))

    common_airports = set(inbound_by_airport.keys()).intersection(
        set(outbound_by_airport.keys())
    )

    candidate_records = []

    for airport in common_airports:
        inbound_group = inbound_by_airport[airport]
        outbound_group = outbound_by_airport[airport].sort_values(
            "scheduled_departure_utc"
        )

        outbound_dep_utc_values = outbound_group["scheduled_departure_utc"].values

        for _, in_row in inbound_group.iterrows():
            arr_utc = in_row["scheduled_arrival_utc"]
            if pd.isna(arr_utc):
                continue

            min_time = (arr_utc + min_delta).to_datetime64()
            max_time = (arr_utc + max_delta).to_datetime64()

            # Binary search range for feasible outbound flights
            left_idx = np.searchsorted(outbound_dep_utc_values, min_time, side="left")
            right_idx = np.searchsorted(outbound_dep_utc_values, max_time, side="right")

            if left_idx >= right_idx:
                continue

            feasible_outbound = outbound_group.iloc[left_idx:right_idx]

            for _, out_row in feasible_outbound.iterrows():
                # Prevent self-pairing (same flight_id)
                if in_row["flight_id"] == out_row["flight_id"]:
                    continue

                # Filter circular connection (origin == destination) if not allowed
                if not allow_circular and in_row["origin"] == out_row["destination"]:
                    continue

                # Carrier filter
                is_same_carrier = in_row["carrier"] == out_row["carrier"]
                if same_carrier_only and not is_same_carrier:
                    continue

                # Calculate scheduled connection time in minutes
                sched_dep_utc = out_row["scheduled_departure_utc"]
                sched_conn_time = (
                    sched_dep_utc - arr_utc
                ).total_seconds() / 60.0

                # Calculate actual connection time if actual timestamps exist
                act_conn_time = np.nan
                if (
                    "actual_arrival_utc" in in_row
                    and "actual_departure_utc" in out_row
                    and pd.notna(in_row["actual_arrival_utc"])
                    and pd.notna(out_row["actual_departure_utc"])
                ):
                    act_conn_time = (
                        out_row["actual_departure_utc"] - in_row["actual_arrival_utc"]
                    ).total_seconds() / 60.0

                rec = {
                    "inbound_flight_id": in_row["flight_id"],
                    "outbound_flight_id": out_row["flight_id"],
                    "inbound_carrier": in_row["carrier"],
                    "outbound_carrier": out_row["carrier"],
                    "is_same_carrier": is_same_carrier,
                    "origin": in_row["origin"],
                    "connection_airport": airport,
                    "destination": out_row["destination"],
                    "connection_route": f"{in_row['origin']}-{airport}-{out_row['destination']}",
                    "inbound_scheduled_departure_utc": in_row.get("scheduled_departure_utc"),
                    "inbound_scheduled_arrival_utc": arr_utc,
                    "inbound_actual_departure_utc": in_row.get("actual_departure_utc"),
                    "inbound_actual_arrival_utc": in_row.get("actual_arrival_utc"),
                    "inbound_departure_delay_min": in_row.get("departure_delay_min"),
                    "inbound_arrival_delay_min": in_row.get("arrival_delay_min"),
                    "outbound_scheduled_departure_utc": sched_dep_utc,
                    "outbound_scheduled_arrival_utc": out_row.get("scheduled_arrival_utc"),
                    "outbound_actual_departure_utc": out_row.get("actual_departure_utc"),
                    "outbound_actual_arrival_utc": out_row.get("actual_arrival_utc"),
                    "outbound_departure_delay_min": out_row.get("departure_delay_min"),
                    "outbound_arrival_delay_min": out_row.get("arrival_delay_min"),
                    "scheduled_connection_time_min": sched_conn_time,
                    "actual_connection_time_min": act_conn_time,
                    "connection_buffer_min": sched_conn_time - min_connection_min,
                }
                candidate_records.append(rec)

    if not candidate_records:
        return pd.DataFrame()

    connections_df = pd.DataFrame(candidate_records)
    return connections_df


def validate_candidate_connections(
    connections_df: pd.DataFrame,
    min_connection_min: int = 45,
    max_connection_min: int = 240,
) -> dict:
    """
    Validate candidate connections for data integrity and business rules.

    Checks performed:
      - Total connection count
      - Duplicate flight pairings (inbound_flight_id, outbound_flight_id)
      - Self-connections (inbound_flight_id == outbound_flight_id)
      - Invalid connection times (< min_connection_min or > max_connection_min)
      - Airport mismatch (inbound destination != connection_airport or outbound origin != connection_airport)
      - Circular connections (origin == destination)
    """
    if connections_df.empty:
        return {
            "total_connections": 0,
            "duplicate_pairings": 0,
            "self_connections": 0,
            "under_min_time_violations": 0,
            "over_max_time_violations": 0,
            "airport_mismatches": 0,
            "circular_connections": 0,
        }

    checks = {}

    checks["total_connections"] = len(connections_df)

    checks["duplicate_pairings"] = connections_df.duplicated(
        subset=["inbound_flight_id", "outbound_flight_id"]
    ).sum()

    checks["self_connections"] = (
        connections_df["inbound_flight_id"] == connections_df["outbound_flight_id"]
    ).sum()

    checks["under_min_time_violations"] = (
        connections_df["scheduled_connection_time_min"] < min_connection_min
    ).sum()

    checks["over_max_time_violations"] = (
        connections_df["scheduled_connection_time_min"] > max_connection_min
    ).sum()

    checks["circular_connections"] = (
        connections_df["origin"] == connections_df["destination"]
    ).sum()

    return checks

