import numpy as np
import pandas as pd


"""
Candidate Flight Connection Generator Module.

DISTINCTION NOTICE:
-------------------
The connections generated by this module are schedule-feasible CANDIDATE flight connections
constructed strictly from published flight schedules and operational timestamps (UTC).
They DO NOT represent observed passenger bookings, passenger flow, ticketed itineraries,
or PNR / ticket data. They indicate pure operational network connectivity options between
inbound and outbound flight legs.
"""


REQUIRED_COLUMNS = [
    "flight_id",
    "carrier",
    "origin",
    "destination",
    "scheduled_departure_utc",
    "scheduled_arrival_utc",
]


def validate_flight_fact_schema(df: pd.DataFrame) -> None:
    """
    Validate that the input dataframe contains all required columns for connection generation.
    """
    missing = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError(
            f"Input dataframe is missing required columns for connection generation: {missing}. "
            f"Expected Fact_Flight_Operation schema columns."
        )


def generate_candidate_connections(
    df: pd.DataFrame,
    min_connection_min: int = 45,
    max_connection_min: int = 240,
    same_carrier_only: bool = False,
    filter_cancelled: bool = True,
    allow_circular: bool = False,
) -> pd.DataFrame:
    """
    Generate schedule-feasible candidate flight connections from Fact_Flight_Operation data.

    A candidate connection is defined as a two-leg flight sequence:
        Flight A (Inbound):  origin -> connection_airport
        Flight B (Outbound): connection_airport -> destination

    Feasibility condition:
        min_connection_min <= (outbound.scheduled_departure_utc - inbound.scheduled_arrival_utc) <= max_connection_min

    Parameters:
        df (pd.DataFrame): Fact_Flight_Operation table containing flight segments.
        min_connection_min (int): Minimum connection window in minutes (default 45 min).
        max_connection_min (int): Maximum connection window in minutes (default 240 min).
        same_carrier_only (bool): If True, restrict to online connections (same carrier). Default False.
        filter_cancelled (bool): If True, exclude cancelled or diverted flights. Default True.
        allow_circular (bool): If True, allow connections where origin == destination (round-trip). Default False.

    Returns:
        pd.DataFrame: Candidate connection pairs with preserved inbound/outbound timestamps,
                      connection metrics, and flight metadata.
    """
    validate_flight_fact_schema(df)

    if df.empty:
        return pd.DataFrame()

    # Filter invalid or missing UTC timestamps
    valid_df = df[
        df["scheduled_arrival_utc"].notna() & df["scheduled_departure_utc"].notna()
    ].copy()

    # Filter cancelled / diverted flights if requested
    if filter_cancelled:
        if "is_cancelled" in valid_df.columns:
            valid_df = valid_df[valid_df["is_cancelled"] == False]
        if "is_diverted" in valid_df.columns:
            valid_df = valid_df[valid_df["is_diverted"] == False]

    if valid_df.empty:
        return pd.DataFrame()

    min_delta = np.timedelta64(min_connection_min, "m")
    max_delta = np.timedelta64(max_connection_min, "m")

    # Group by airport (inbound arrives at destination, outbound departs from origin)
    inbound_by_airport = dict(list(valid_df.groupby("destination")))
    outbound_by_airport = dict(list(valid_df.groupby("origin")))

    common_airports = set(inbound_by_airport.keys()).intersection(
        set(outbound_by_airport.keys())
    )

    airport_dfs = []

    for airport in common_airports:
        inbound_k = inbound_by_airport[airport].reset_index(drop=True)
        outbound_k = (
            outbound_by_airport[airport]
            .sort_values("scheduled_departure_utc")
            .reset_index(drop=True)
        )

        arr_utc_values = inbound_k["scheduled_arrival_utc"].values
        dep_utc_values = outbound_k["scheduled_departure_utc"].values

        min_times = arr_utc_values + min_delta
        max_times = arr_utc_values + max_delta

        # Fast vectorized binary search for range indices per inbound flight
        left_idx = np.searchsorted(dep_utc_values, min_times, side="left")
        right_idx = np.searchsorted(dep_utc_values, max_times, side="right")

        counts = right_idx - left_idx
        valid_mask = counts > 0
        if not valid_mask.any():
            continue

        matching_inbound_idx = np.where(valid_mask)[0]
        matching_counts = counts[valid_mask]

        # Vectorized index expansion
        inbound_rep_idx = np.repeat(matching_inbound_idx, matching_counts)
        outbound_matched_idx = np.concatenate(
            [
                np.arange(l, r)
                for l, r in zip(left_idx[valid_mask], right_idx[valid_mask])
            ]
        )

        in_ids = inbound_k["flight_id"].values[inbound_rep_idx]
        out_ids = outbound_k["flight_id"].values[outbound_matched_idx]

        in_origs = inbound_k["origin"].values[inbound_rep_idx]
        out_dests = outbound_k["destination"].values[outbound_matched_idx]

        in_carrs = inbound_k["carrier"].values[inbound_rep_idx]
        out_carrs = outbound_k["carrier"].values[outbound_matched_idx]

        # Vectorized business rule filtering
        mask = in_ids != out_ids
        if not allow_circular:
            mask = mask & (in_origs != out_dests)
        if same_carrier_only:
            mask = mask & (in_carrs == out_carrs)

        if not mask.any():
            continue

        final_in = inbound_rep_idx[mask]
        final_out = outbound_matched_idx[mask]

        sub_in = inbound_k.iloc[final_in].reset_index(drop=True)
        sub_out = outbound_k.iloc[final_out].reset_index(drop=True)

        sched_conn = (
            sub_out["scheduled_departure_utc"] - sub_in["scheduled_arrival_utc"]
        ).dt.total_seconds() / 60.0

        act_conn = np.nan
        if (
            "actual_arrival_utc" in sub_in.columns
            and "actual_departure_utc" in sub_out.columns
        ):
            act_conn = (
                sub_out["actual_departure_utc"] - sub_in["actual_arrival_utc"]
            ).dt.total_seconds() / 60.0

        conn_df = pd.DataFrame(
            {
                "inbound_flight_id": sub_in["flight_id"],
                "outbound_flight_id": sub_out["flight_id"],
                "inbound_carrier": sub_in["carrier"],
                "outbound_carrier": sub_out["carrier"],
                "is_same_carrier": sub_in["carrier"] == sub_out["carrier"],
                "origin": sub_in["origin"],
                "connection_airport": airport,
                "destination": sub_out["destination"],
                "connection_route": sub_in["origin"]
                + "-"
                + airport
                + "-"
                + sub_out["destination"],
                "inbound_scheduled_departure_utc": sub_in["scheduled_departure_utc"],
                "inbound_scheduled_arrival_utc": sub_in["scheduled_arrival_utc"],
                "inbound_actual_departure_utc": sub_in.get("actual_departure_utc"),
                "inbound_actual_arrival_utc": sub_in.get("actual_arrival_utc"),
                "inbound_departure_delay_min": sub_in.get("departure_delay_min"),
                "inbound_arrival_delay_min": sub_in.get("arrival_delay_min"),
                "outbound_scheduled_departure_utc": sub_out[
                    "scheduled_departure_utc"
                ],
                "outbound_scheduled_arrival_utc": sub_out.get(
                    "scheduled_arrival_utc"
                ),
                "outbound_actual_departure_utc": sub_out.get("actual_departure_utc"),
                "outbound_actual_arrival_utc": sub_out.get("actual_arrival_utc"),
                "outbound_departure_delay_min": sub_out.get("departure_delay_min"),
                "outbound_arrival_delay_min": sub_out.get("arrival_delay_min"),
                "scheduled_connection_time_min": sched_conn,
                "actual_connection_time_min": act_conn,
                "connection_buffer_min": sched_conn - min_connection_min,
            }
        )
        airport_dfs.append(conn_df)

    if not airport_dfs:
        return pd.DataFrame()

    connections_df = pd.concat(airport_dfs, ignore_index=True)
    return connections_df


def validate_candidate_connections(
    connections_df: pd.DataFrame,
    min_connection_min: int = 45,
    max_connection_min: int = 240,
) -> dict:
    """
    Validate candidate connections for data integrity and business rules.

    Checks performed:
      - Total connection count
      - Duplicate flight pairings (inbound_flight_id, outbound_flight_id)
      - Self-connections (inbound_flight_id == outbound_flight_id)
      - Invalid connection times (< min_connection_min or > max_connection_min)
      - Airport mismatch (inbound destination != connection_airport or outbound origin != connection_airport)
      - Circular connections (origin == destination)
    """
    if connections_df.empty:
        return {
            "total_connections": 0,
            "duplicate_pairings": 0,
            "self_connections": 0,
            "under_min_time_violations": 0,
            "over_max_time_violations": 0,
            "airport_mismatches": 0,
            "circular_connections": 0,
        }

    checks = {}

    checks["total_connections"] = len(connections_df)

    checks["duplicate_pairings"] = int(
        connections_df.duplicated(
            subset=["inbound_flight_id", "outbound_flight_id"]
        ).sum()
    )

    checks["self_connections"] = int(
        (
            connections_df["inbound_flight_id"]
            == connections_df["outbound_flight_id"]
        ).sum()
    )

    checks["under_min_time_violations"] = int(
        (
            connections_df["scheduled_connection_time_min"] < min_connection_min
        ).sum()
    )

    checks["over_max_time_violations"] = int(
        (
            connections_df["scheduled_connection_time_min"] > max_connection_min
        ).sum()
    )

    checks["circular_connections"] = int(
        (connections_df["origin"] == connections_df["destination"]).sum()
    )

    return checks
