import numpy as np
import pandas as pd


"""
Connection Reliability & Risk Analysis Module.

Calculates operational connection reliability, effective connection time,
and missed connection risk based on actual flight arrival/departure timestamps.
"""


def calculate_connection_reliability(
    connections_df: pd.DataFrame,
    minimum_transfer_time_min: int = 30,
) -> pd.DataFrame:
    """
    Calculate operational connection performance metrics for candidate flight connections.

    Parameters:
        connections_df (pd.DataFrame): Candidate connection pairs generated by generator module.
        minimum_transfer_time_min (int): Minimum required transfer time at connection airport (default 30 min).

    Returns:
        pd.DataFrame: Aggregated connection reliability metrics grouped by connection airport or carrier pair.
    """
    if connections_df.empty:
        return pd.DataFrame()

    df = connections_df.copy()

    # Effective connection time = (outbound actual departure) - (inbound actual arrival)
    if "actual_connection_time_min" not in df.columns:
        df["actual_connection_time_min"] = (
            df["outbound_actual_departure_utc"] - df["inbound_actual_arrival_utc"]
        ).dt.total_seconds() / 60.0

    # Missed connection occurs if actual connection time < minimum required transfer time
    # or if inbound/outbound legs are cancelled
    df["is_missed_connection"] = (
        df["actual_connection_time_min"] < minimum_transfer_time_min
    )

    reliability = (
        df.groupby(["connection_airport", "is_same_carrier"])
        .agg(
            total_candidate_connections=("inbound_flight_id", "count"),
            successful_connections=(
                "is_missed_connection",
                lambda x: (x == False).sum(),
            ),
            missed_connections=(
                "is_missed_connection",
                lambda x: (x == True).sum(),
            ),
            average_scheduled_connection_time=(
                "scheduled_connection_time_min",
                "mean",
            ),
            average_actual_connection_time=(
                "actual_connection_time_min",
                "mean",
            ),
            median_actual_connection_time=(
                "actual_connection_time_min",
                "median",
            ),
        )
        .reset_index()
    )

    reliability["connection_success_rate"] = (
        reliability["successful_connections"]
        / reliability["total_candidate_connections"]
    )
    reliability["missed_connection_rate"] = (
        reliability["missed_connections"]
        / reliability["total_candidate_connections"]
    )

    return reliability


def calculate_missed_connection_risk(
    connections_df: pd.DataFrame,
    critical_buffer_min: int = 15,
) -> pd.DataFrame:
    """
    Analyze risk exposure of connections based on inbound arrival delays.
    """
    if connections_df.empty:
        return pd.DataFrame()

    df = connections_df.copy()

    # Absorptive buffer remaining = scheduled_connection_time_min - inbound_arrival_delay_min
    df["remaining_buffer_min"] = (
        df["scheduled_connection_time_min"] - df["inbound_arrival_delay_min"].fillna(0)
    )

    df["is_high_risk_connection"] = (
        df["remaining_buffer_min"] < critical_buffer_min
    )

    return df

